apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd
  namespace: openshift-gitops
spec:
  destination:
    namespace: httpd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: httpd
    repoURL: https://github.com/mriensch/argo-test-app
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
