apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
 name: classification-banner
spec:
 text: Unclassified ##Classification Level
 location: BannerTopBottom ##Other options are BannerBottom, BannerTopBottom
 color: '#FFFFFF' ##Hexcode for white text color
 backgroundColor: '#F97669' ##Hexcode for banner background color